### ISSUE TITLE
Falla en el Autograding ...

### ISSUE THREAD

**Issue by ricardo-quintero** [itc-mcc/strategy-JonaStark#2]
Estimado @JonaStark,

Algo sucede con tu proyecto que no pasa las pruebas de Autograding.

**Comment by ricardo-quintero** [comment]
Me notificas por este medio que decidiste ...

**Comment by JonaStark** [comment]
https://github.com/JonaStark/strategy-JonaStark/runs/2189142734?check_suite_focus=true

Hola Doc a mi me sale bien
Le paso el link

***@***.***D72A16.76040120]

Es que tengo otro proyecto pero no se porque me salió mal y tengo dos repositorios



De: Ricardo ***@***.***>
Enviado: lunes, 5 de abril de 2021 12:06 p. m.
Para: ***@***.***>
CC: JONATHAN IVAN ROLDAN ***@***.***>; ***@***.***>
Asunto: Re: [itc-mcc/strategy-JonaStark] Falla en el Autograding ... (#2)


Me notificas por este medio que decidiste ...

**Comment by ricardo-quintero** [comment]
Ok, ya quedó ...

Gracias.

**Comment by JonaStark** [comment]
Muchas gracias por notificarme... disculpe las molestias doc

Saludos!!

De: Ricardo ***@***.***>
Enviado: lunes, 5 de abril de 2021 12:45 p. m.
Para: ***@***.***>
CC: JONATHAN IVAN ROLDAN ***@***.***>; ***@***.***>
Asunto: Re: [itc-mcc/strategy-JonaStark] Falla en el Autograding ... (#2)


Ok, ya quedó ...

Gracias.
